### ISSUE TITLE
Mis-optimized if imported url has ";"

### ISSUE THREAD

**Issue by kevinptt0323** [futtta/autoptimize#122] opened 2017-12-06 09:16 UTC
Add additional css:
```
@import url("foo.css?a&#038;b");
@import url("bar.css");
```

The optimized css will become:
```
@import url(//example.com/test.css?a&#038;@import url("//example.com/bar.css");
```

[Ref](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeStyles.php#L272)

**Comment by futtta** [comment] 2017-12-09 15:23
did some tests on regex101.com; while the change fixes the bug for the example given, it does not match a simple list of example imports as found on [this mozilla-developer page](https://developer.mozilla.org/en-US/docs/Web/CSS/%40import
)

compare [regex101.com with new regex](https://regex101.com/r/aqMs30/2) with this [regex101.com test with old regex](https://regex101.com/r/aqMs30/1)

so back to the drawing board ...

**Comment by futtta** [comment] 2017-12-09 16:07
making the regex greedy seems to work for all examples; https://regex101.com/r/aqMs30/4

thoughts?

**Comment by kevinptt0323** [comment] 2017-12-09 17:59
It will not work if there is multiple `@import` rules in a single line if you enable greedy.
Example:
```
@import url("bar.css"); @import url("bar.css");
```

And it will mis-match in some wrong cases. (Maybe we can ignore it right now)
```
@import 'custom.css";
```

**Comment by kevinptt0323** [comment] 2017-12-09 18:37
I think [this](https://regex101.com/r/qrfWCP/4) is correct.

Thanks to [kevva/import-regex](https://github.com/kevva/import-regex).

**Comment by futtta** [comment] 2017-12-09 19:46
well, we have 3 options to compare;

1. original regex; chokes on semi-colons (as per your original report), cfr. https://regex101.com/r/aqMs30/5, all else is OK, low severity (it's very unusual to see that kind of URL for a CSS import)
2. original regex turned greedy, does not capture multiple imports on same line, cfr. https://regex101.com/r/aqMs30/6, severity MAJOR (multiple imports on the same line are probably not exceptional)
3. your proposal based on https://github.com/kevva/import-regex, which does not match the quirky imports, cfr. https://regex101.com/r/qrfWCP/5 severity MINOR (there's a case to be made for AO not catching those, it's _very_ buggy CSS), but it did work before so it would be a regression which I'm not fond of ...

So going greedy (2) is out and (3) indeed is not bad, but it is not perfect (yet).

**Comment by kevinptt0323** [comment] 2017-12-09 20:13
I update my regex to version 6 (https://regex101.com/r/qrfWCP/6).

The last three `@import`'s are **invalid** rules according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import), so I think my solution is almost feasible.

BTW, I also do some [works](https://github.com/kevva/import-regex/pull/4) on kevva/import-regex since their code has some minor bugs, too. I will give you some feedbacks if there is any updates.

**Comment by futtta** [comment] 2017-12-09 20:17
what's the functional difference between your v5 & v6, seems to match same imports, no?

**Comment by kevinptt0323** [comment] 2017-12-10 06:19
I change the regex for the part of media query from `(?:(?:[^,^;]+)(?:,(?:[^,^;]+))*)` to `(?:[^,;"']+(?:,[^,;"']+)*)`

v5 will match `@import "custom.css" "custom.css";`, which is invalid.

**Comment by zytzagoo** [comment] 2017-12-11 09:09
@futtta noup, no tests covering that currently, but what's the exact issue in the original report?

That the `b` character is eaten/missing from the resulting minified version? Because that's not happening in my version when running this test:

```php

    public function test_css_import_semicolon_url_issue_122()
    {
        $in = <<<CSS
@import url("foo.css?a&#038;b");
@import url("bar.css");
CSS;

        $expected = '@import url("foo.css?a&#038;b");@import url("bar.css");';

        $instance = new autoptimizeStyles($in);
        $actual   = $instance->run_minifier_on($in);
        $this->assertEquals($expected, $actual);
    }
```

This test appears to pass just fine on my fork? I might not be hitting the same code paths though or something... Can we get the absolute simplest possible test case that fails?

**Comment by futtta** [comment] 2017-12-11 09:49
the main issue is that the closing bracket `)` is missing from the first import, breaking both @import. the linked test-case if correct (albeit only tests this specific use-case, cfr. https://regex101.com/r/qrfWCP/6 for a more exhaustive set of examples.

**Comment by futtta** [comment] 2017-12-11 09:53
Weird your test passes for you, as the "culprit"-regex is the same in your fork;

`while ( preg_match_all( '#@import.*(?:;|$)#Um', $thiscss_nocomments, $matches ) ) {`

**Comment by zytzagoo** [comment] 2017-12-11 10:06
Yeah, that's what I was thinking too when talking about hitting different code paths... Could it be that the difference is when there are actual (locally available) files being referenced in those import statements? Which then triggers some other code etc. Gonna dig deeper when I have a chance...

**Comment by zytzagoo** [comment] 2017-12-11 10:09
First look: test passes because it's not actually calling the import-parsing parts of the code at all, it's just running the css minifiers on it :)

**Comment by futtta** [comment] 2017-12-11 10:14
so that would be a bug in your fork @zytzagoo, no, as it should call the import-parsing?

**Comment by zytzagoo** [comment] 2017-12-11 10:14
nah, bug in how the test is set up

**Comment by zytzagoo** [comment] 2017-12-11 10:34
The problem here is how to test this in isolation -- that regex and processing of results is highly coupled to everything else going on there...

But yes, I'm now hitting the same code path and exhibiting the same bug, it's just that it's really hard to get a simple test case set up for this + get processed results out to compare in a test case...

Testing it out like this now:
```php
    public function test_css_import_semicolon_url_issue_122()
    {
        $in = <<<CSS
<style type="text/css">
@import url("foo.css?a&#038;b");
@import url("bar.css");
</style>
CSS;

        $expected = '<style type="text/css" media="all">@import url(http://cdn.example.org/foo.css?a&#038;b);@import url(http://cdn.example.org/bar.css);</style><!--noptimize--><!-- Autoptimize found a problem with the HTML in your Theme, tag `title` missing --><!--/noptimize-->';

        $conf = autoptimizeConfig::instance();
        $options = array(
            'autoptimizeStyles' => array(
                'justhead' => $conf->get('autoptimize_css_justhead'),
                'datauris' => $conf->get('autoptimize_css_datauris'),
                'defer' => $conf->get('autoptimize_css_defer'),
                'defer_inline' => $conf->get('autoptimize_css_defer_inline'),
                'inline' => $conf->get('autoptimize_css_inline'),
                'css_exclude' => $conf->get('autoptimize_css_exclude'),
                'cdn_url' => $conf->get('autoptimize_cdn_url'),
                'include_inline' => $conf->get('autoptimize_css_include_inline'),
                'nogooglefont' => $conf->get('autoptimize_css_nogooglefont')
            )
        );

        $instance = new autoptimizeStyles($in);
        $instance->read($options['autoptimizeStyles']);
        $instance->minify();
        $instance->cache();
        $actual = $instance->getcontent();
        $this->assertEquals($expected, $actual);
    }
```
With the regex from https://regex101.com/r/qrfWCP/6 does indeed result in the expected output.

But that is by no means a unit test now :) (doing so many things it's not even funny)

**Comment by futtta** [comment] 2017-12-11 11:00
OK, let's go for Kevin's regex, @kevinptt0323 can you do a pull request?

@zytzagoo yeah, AO is not written with a "test first" approach I'm afraid ;-)

**Comment by kevinptt0323** [comment] 2017-12-11 13:10
OK, I'll do a PR.

And I found another bug in `autoptimizeStyles::fixurls`, which will merge 2 css imports in a single line.

**Comment by futtta** [comment] 2017-12-11 13:14
can you explain that other bug here as well @kevinptt0323 ? :-)

**Comment by kevinptt0323** [comment] 2017-12-11 13:22
```
@import "foo.css"; @import "bar.css" (orientation:landscape);
```
will become
```
@import url(//cdn.lecrazyeat.tw/foo.css)(orientation:landscape);
```
This bug exist in the current version.

**Closed** 2017-12-11 13:57 UTC

**Comment by zytzagoo** [comment] 2017-12-11 15:52
I cannot seem to repro the thing mentioned in https://github.com/futtta/autoptimize/issues/122#issuecomment-350722648 with these two testcases:

```php
    public function test_fixurls_with_at_imports_and_media_queries()
    {
        $in  = '@import "foo.css"; @import "bar.css" (orientation:landscape);';
        $exp = '@import url(//example.org/wp-content/themes/my-theme/foo.css); @import url(//example.org/wp-content/themes/my-theme/bar.css) (orientation:landscape);';

        $actual = autoptimizeStyles::fixurls(ABSPATH . 'wp-content/themes/my-theme/style.css', $in);
        $this->assertEquals($exp, $actual);
    }

    public function test_aostyles_at_imports_with_media_queries()
    {
        $in = <<<CSS
<style type="text/css">
@import "foo.css"; @import "bar.css" (orientation:landscape);
</style>
CSS;

        $expected = '<style type="text/css" media="all">@import url(http://cdn.example.org/foo.css);@import url(http://cdn.example.org/bar.css)(orientation:landscape);</style><!--noptimize--><!-- Autoptimize found a problem with the HTML in your Theme, tag `title` missing --><!--/noptimize-->';

        $conf = autoptimizeConfig::instance();
        $options = array(
            'autoptimizeStyles' => array(
                'justhead' => $conf->get('autoptimize_css_justhead'),
                'datauris' => $conf->get('autoptimize_css_datauris'),
                'defer' => $conf->get('autoptimize_css_defer'),
                'defer_inline' => $conf->get('autoptimize_css_defer_inline'),
                'inline' => $conf->get('autoptimize_css_inline'),
                'css_exclude' => $conf->get('autoptimize_css_exclude'),
                'cdn_url' => $conf->get('autoptimize_cdn_url'),
                'include_inline' => $conf->get('autoptimize_css_include_inline'),
                'nogooglefont' => $conf->get('autoptimize_css_nogooglefont')
            )
        );

        $instance = new autoptimizeStyles($in);
        $instance->read($options['autoptimizeStyles']);
        $instance->minify();
        $instance->cache();

        $actual = $instance->getcontent();
        $this->assertEquals($expected, $actual);
    }
```

Both of the above tests pass for me (again, not saying there isn't an issue somewhere else, but where exactly? The `$expected` output above seems ok to me).

Even returning to the old (broken) regex doesn't change the output of these two tests (which is expected since there are no semicolon-related "triggers" in the above tests/urls, no?)

**Comment by kevinptt0323** [comment] 2017-12-11 17:56
It is strange. I test the following code:
```php
<?php
$css = '@import "foo.css"; @import "bar.css" (orientation:landscape);';
$res = preg_replace( '#@import ("|\')(.+?)\.css.*("|\')#', '@import url("${2}.css")', $css );
echo $res;
// @import url("foo.css") (orientation:landscape);
```

PHP 7.0.24

**Comment by zytzagoo** [comment] 2017-12-11 20:46
probably, yes (new issue) -- the code you posted above acts the way you wrote, yes, but there is some more magic stuff inside fixurls() that "fixes" things back (if the result of above preg_replace matches self::ASSETS_REGEX, roughly speaking)

whether that should be like that (and how intuitive it is) is another topic :)

**Comment by futtta** [comment] 2017-12-11 21:15
Somewhat opportunistic; if the test of the full fixurl function doesn't fail, then there is no (major) issue. A fixurl-rewrite based on a new and better regex is something we _could_ include at a later stage, but it would not be my priority now as I'm focusing on adding functionality rather then fixing something which might be ugly but is not broken.

If tests of the full fixurl() would fail, then we have a totally different situation off course :-)
