### ISSUE TITLE
Gzip output not used. 

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [futtta/autoptimize#76] opened 2017-01-06 17:54 UTC
Hi Frank,

Your plugin now supports creation of pre-gzipped files. I have enabled them using:

`add_filter('autoptimize_filter_cache_create_static_gzip','__return_true');`

However this file doesn't seem to be used and the server is gzipping everytime. My conclusion is based on the observation that the content-length as seen from Chrome development tools is higher than the static gzip file. 

I think you need to add headers in htaccess asking the server to use the gzip file instead of dynamically compressing. 

Code [here](https://httpd.apache.org/docs/2.4/mod/mod_deflate.html)

```
<IfModule mod_headers.c>
    # Serve gzip compressed CSS files if they exist 
    # and the client accepts gzip.
    RewriteCond "%{HTTP:Accept-encoding}" "gzip"
    RewriteCond "%{REQUEST_FILENAME}\.gz" -s
    RewriteRule "^(.*)\.css" "$1\.css\.gz" [QSA]

    # Serve gzip compressed JS files if they exist 
    # and the client accepts gzip.
    RewriteCond "%{HTTP:Accept-encoding}" "gzip"
    RewriteCond "%{REQUEST_FILENAME}\.gz" -s
    RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]


    # Serve correct content types, and prevent mod_deflate double gzip.
    RewriteRule "\.css\.gz$" "-" [T=text/css,E=no-gzip:1]
    RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1]


    <FilesMatch "(\.js\.gz|\.css\.gz)$">
      # Serve correct encoding type.
      Header append Content-Encoding gzip

      # Force proxies to cache gzipped & 
      # non-gzipped css/js files separately.
      Header append Vary Accept-Encoding
    </FilesMatch>
</IfModule>
```

**Comment by futtta** [comment] 2017-01-06 20:00
that's correct, when enabling gz creation with the filter you still have to change your .htaccess (or nginx equivalent). people who can use filters can also change a .htaccess ;-)

**Comment by vijayaraghavanramanan** [comment] 2017-01-09 05:56
True, but won't updates potentially overwrite this?

**Comment by futtta** [comment] 2017-01-09 06:08
changes to your root .htaccess are not overwritten no :)

**Comment by futtta** [comment] 2017-01-09 12:52
closing as intended behavior ;-)

**Closed by futtta** 2017-01-09 12:52 UTC
