### ISSUE TITLE
When activated autoptimize 2.4 is slowing web page load on our website

### ISSUE THREAD

**Issue by blessedOn** [futtta/autoptimize#182] opened 2018-08-14 13:51 UTC
Hi there

I tried to activate the new autoptimize [Version 2.4.0-beta-4] couple of times, but it is causing our website to load really slow and sometimes, pages are taking ages to load. If I desactivated it, and,  use the previous version [Version 2.3.4], the I do not any problem at all. 

Question: Why activating autoptimize [Version 2.4.0-beta-4] is slowing pages load on our website? Is there any option that should not ticked? Cause I am confused.

**Comment by futtta** [comment] 2018-08-14 16:48
I'd love to dig in to be able to answer your question @blessedOn 

Could you test your website on https://webpagetest.org/;

* 1 test with AO 2.3 and one with AO 2.4
* each test with `Number of tests to run` (under "advanced settings") set to 5
* all other settings (e.g. browser, location and bandwidth type) the same between the 2 tests
* and post the 2 resulting test URL's here for me to compare?

thanks!
frank

**Comment by blessedOn** [comment] 2018-08-14 17:27
Hi frank

Here is results of tests you requested:

1. test with AO 2.3. URL of test results:
https://webpagetest.org/result/180814_KD_85fac1ada1394f6aa8c0fb3c7ce746af/

2. test with AO 2.4. URL of test results:
https://webpagetest.org/result/180814_VA_37d76f34682463a74c117dedbf18654e/

I hope this is what you wanted me to do.

Regards

Roberto

Le mar. 14 août 2018 à 17:48, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment] 2018-08-14 19:15
Merci @blessedOn :-)

I've quickly reviewd and the results (this far) aren't entirely conclusive, so could you redo them but with 9 (the maximum) `Number of test to run`?

**Comment by blessedOn** [comment] 2018-08-15 00:06
I will send you the other requested test later on today. It’s now 01:04 am
in the morning here. I am in Europe and it’s bedtime.

Le mar. 14 août 2018 à 20:15, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment] 2018-08-15 06:40
Pas de soucis, je suis en Europe aussi (partie Nord du Belgique) :-)

**Comment by futtta** [comment] 2018-08-16 16:57
Any update on this @blessedOn ? :-)

**Comment by blessedOn** [comment] 2018-08-16 22:00
Hi Frank,

Je suis en Irlande du Sud :-)

In relation to the issue with Autoptimize 2.4, I tried to do some
troubleshooting by myself and it seems to be responding fine for now. What
I did is that I have désactivé the plugin [Autoptimize 2.4], clear all
cache from the website and reinstall it. And results are quite good and
Autoptimize 2.4 is now responding ok. But I am still keeping an eye on it
to make sure that things run smoothly. If any issue arises then I will have
no other choice to run the tests you requested.

Now, I have also noticed that

(1) the size of the cache is increasing very quickly within 24 hours
because I have “Agréger aussi les JS inline ?” selected, to solve this
caching problem, I am clearing Autoptimize cache every 5 or 6 hours. Is it
necessary to have this option selected?

(2) After running page speed on Google PageSpeed Insights, I am getting 1
blocking script resources and 2 blocking CSS resources, coming from Google
APIS's:

a. https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
b. https://fonts.googleapis.com/css?family=Droid+Sans%3Aregular%2C700
c.
https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&subset=latin%2Clatin-ext


Is there any option on Autoptimize 2.4 that can help in relation the above
block resources?

Regards,

Roberto

Le jeu. 16 août 2018 à 17:57, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment] 2018-08-17 06:11
morning Roberto :-)

-> regarding cache; by default "aggregate inline JS" is active to avoid just that, so I would either de-select that or try to exclude just the cache-busting inline JS from optimization
-> regarding the google fonts calls; the "optimize google fonts"-options on AO's "extra" tab could help
-> https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js cannot not optimized because it's not a local file, but even if you would be usin `wp-includes/js/jquery/jquery.js` you would likely have to keep on excluding it because you have inline JS that requires jQuery to be available early.

I'll close this issue as you confirmed there is not performance issue in 2.4, but feel free to follow up on the above :)

Bien à vous,
frank

**Closed by futtta** 2018-08-17 06:11 UTC

**Comment by futtta** [comment] 2018-08-17 12:36
my bad; by default "aggregate inline JS" is NOT active :-)

**Comment by blessedOn** [comment] 2018-08-17 16:38
Hi Frank

Thank you for suggestion to use options on Autoptimize’s “Extra” tab in
order to deal with Google fonts calls. In the extra tab, under “Google
Fonts” I use the option “Combine and preload in head (fonts load late, but
are not render-blocking)”, that actually helped to clear the two blocking
CSS resources I was getting on Google pageSpeed test.

Now, I am still getting *1 blocking script resources* in the Google
pageSpeeg test. I read further down on the “Extra” tab page on the
Autoptimize, and I saw an option “Fichiers JavaScript asynchrones
(utilisateurs avancés)” - I have not use it yet - which has the following
message: “

Comma-separated list of local or 3rd party JS-files that should loaded with
the async flag. JS-files from your own site will be automatically excluded
if added here. Configuration of async javascript is easier and more
flexible using the "Async Javascript
<https://wordpress.org/plugins/async-javascript>" plugin. Click here to
install and activate it.
<https://fr.kongotimes.info/wp-admin/plugin-install.php?s=async+javascript&tab=search&type=term>
“
Would this option help to clear the 1 blocking script resources I am
getting by intering the full URL in the space provided? Also, as stated in
the message above, do I have to install and activate the suggested plugin
in order to deal with this issue? Or do both, meaning that entering the 3rd
party JS-files in the space provided and install the plugin. I am a little
confused.

Regards

Roberto

Le ven. 17 août 2018 à 13:36, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment] 2018-08-17 16:53
> I am still getting *1 blocking script resources* in the Google pageSpeeg test.

Which one? if this is jquery, asyncing it (in AO or using Async JS) would probably break some functionality of your site (as you have inline JS that depends on jQuery being available early).

Regarding using the async field in AO or AsyncJS; you don't need to do both, you can pick one. AsyncJS is a bit easier to work with maybe? :)

**Comment by blessedOn** [comment] 2018-08-17 16:59
It is this one here:
https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js


Le ven. 17 août 2018 à 17:53, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment] 2018-08-17 18:00
indeed; jQuery. you can try asyncing it, but it will probably brake some of your site's functionality.
