### ISSUE TITLE
A3 Lazy Load and Shortpixel-Optimization not working

### ISSUE THREAD

**Issue by christophcemper** [futtta/autoptimize#165] opened 2018-06-11 09:45 UTC
When lazy load (using A3 Lazy Load) is enabled, then the Shortpixel-Optimization is not working.

It seems like only the spinner gif is sent to automation, but not the actual (redirected) image

**Comment by futtta** [comment] 2018-06-11 13:33
On it :-)

**Comment by futtta** [comment] 2018-06-11 18:41
OK, [just committed some significant improvements in the img src/ srcset parsing logic](https://github.com/futtta/autoptimize/commit/9422b58bd24666f804e2d2e2dfb2a0f64cb95ec1), including support for A3 Lazy Load. Would be great if you could [download](https://github.com/futtta/autoptimize/archive/beta.zip) & test the latest build @christophcemper

**Comment by christophcemper** [comment] 2018-06-12 16:32
Oh wow - that was quick! awesome

**Comment by futtta** [comment] 2018-06-12 16:36
as in; "great, I'll test" or "tested and confirmed working" @christophcemper ? :-)

**Comment by christophcemper** [comment] 2018-06-12 17:23
great, I'll test

**Comment by christophcemper** [comment] 2018-06-12 18:13
There is something nasty going on in this fix.

I only get a white/blank screen when looking at the site logged in as admin.
However, as anon user it appears to work.

Haven't checked the background images yet, those were an issue, too

**Comment by futtta** [comment] 2018-06-12 18:55
Darn .. can't reproduce myself, anything in your php errorlog?

**Comment by christophcemper** [comment] 2018-06-12 19:07
After disabled all caching plugins, clearing everything again and again and enabling I could make it work logged in as well

**Comment by futtta** [comment] 2018-06-12 19:09
strange. and nothing in the php errorlog?

**Comment by christophcemper** [comment] 2018-06-12 19:10
Nothing

**Comment by christophcemper** [comment] 2018-06-12 19:13
Gosh - no - that was a phantom. Still (again?) not working

**Comment by christophcemper** [comment] 2018-06-12 19:14
That's frustrating

**Comment by christophcemper** [comment] 2018-06-12 19:15
Works with Version 2.3.4

**Comment by futtta** [comment] 2018-06-12 19:24
can you in 2.4 beta disable some options to pinpoint?

**Comment by christophcemper** [comment] 2018-06-12 19:38
Yes, did that.

It's the "Optimize HTML Code?" setting. If check this off, it seems to work now

**Comment by christophcemper** [comment] 2018-06-12 20:23
No, that disabled it all. Turning it back on and testing all the other options it's clear, that the shortpixel-code is causing the white/blank screen

**Comment by futtta** [comment] 2018-06-12 20:29
weird that it only breaks when logged in (and that it works for me), makes
it hard(er) to pinpoint.  I'l try to reproduce tomorrow and will review the
code. If you have any idea of what makes your logged-in pages special (any
plugin that does something vaguely related to image), do let me know as
that could help?

**Comment by christophcemper** [comment] 2018-06-13 08:40
Plugins that work in the admin only are

QM - Query monitor
Admin Columns Pro

and on images I had enabled "Optimus HQ" - with the paid license for webp - disabled it for testing now, retrying with shortpixel enabled again

didn't help

the only thing now on error_log is

PHP Warning: require(/nas/content/live/xxx/wp-content/plugins/autoptimize/classes/external/php/plugin-update-checker/plugin-update-checker.php): failed to open stream: No such file or directory in /nas/content/live/xxx/wp-content/plugins/autoptimize-beta/autoptimize.php on line 31, referer: https://xxx.wpengine.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

**Comment by christophcemper** [comment] 2018-06-13 09:04
ALSO - still have TONs of those redirects for the lazy placeholder gif :)

Remove the following redirect chain if possible:

https://api-ai.shortpixel.com/client/q_glossy,ret_img,w_300,h_300/https://xxx.wpengine.com/wp-content/plugins/a3-lazy-load/assets/images/lazy_placeholder.gif
https://xxx..wpengine.com/wp-content/plugins/a3-lazy-load/assets/images/lazy_placeholder.gif


and certainly don't need "Glossy" setting from Shortpixel - where can these settings be changed?

**Comment by futtta** [comment] 2018-06-13 09:32
-> let's focus on the major issue (blank screen) first and foremost. I'll create a debug-version of autoptimizeExtra.php which will do extra error-logging later today.
-> the redirects can happen the first time (if the image isn't optimized & on SP's CDN yet), in which case SP redirects to the original image. the 2nd time you load that page it should not redirect any more?
-> glossy is the "smart default" (because lossy could "uglify" already compressed images) and there is no setting for this. you can however change it with this code snippet;

add_filters( 'autoptimize_filter_extra_imgopt_quality', 'go_lossy' );
function go_lossy() { return "q_lossy"; }

**Comment by futtta** [comment] 2018-06-13 12:17
OK, I created a debug-version of `wp-content/plugins/autoptimize/classes/autoptimizeExtra.php` which [you can find here](https://gist.github.com/futtta/49fad16440e8d7a331ce0b2d564114a9). This will generate a significant amount of start/stop markers for all image-optimization functions in your php errorlog-file. This will hopefully at least allow us to narrow down where in the code the issue you encounter when logged in is located. 

Ideally you copy the "normal" autoptimizeExtra.php to autoptimizeExtra.php_old (or something) and then overwrite the contents of autoptimizeExtra.php with the debug-version. Then visit the site while logged in and harvest the log-info from your php-errorlog and mail that to me at futtta-at-gmail-dot-com.

**Comment by futtta** [comment] 2018-06-14 17:55
have you had the chance to test with the logging version of autoptimizeExtra.php @christophcemper ? or would you prefer a full zip-file to download, or would you like me to test this on your staging-site (you can contact me at futtta-at-gmail-dot-com to discuss offline)? I'd really like to fix this and I can't reproduce so you're my one and only go-to person for this :-)

**Comment by futtta** [comment] 2018-06-17 06:15
fixed :-)

**Closed by futtta** 2018-06-17 06:15 UTC
