### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by S1SYPHOS** [futtta/autoptimize#24] opened 2015-10-28 08:02 UTC
Hey there,
currently I'm working with autoptimize development version and came across some unusual behaviour the other day: the files are being generated, but not referenced in the html output. I already checked file permissions, but nothing even with 777. maybe a bug? Happens both with and without page caching plugin (in my case Cachify).

Thanks for this great plugin and your time,
S1SYPHOS

**Comment by futtta** [comment] 2015-10-28 08:11
hi s1syphos;
some questions;
* does this always occur, or sometimes?
* did (do) you have the same problem with the current release (1.9.4, cfr. https://downloads.wordpress.org/plugin/autoptimize.1.9.4.zip)?
* is the original JS/CSS removed from the HTML, or is that still in place?
* do you see any errors in the phperror logfile?

frank

**Comment by S1SYPHOS** [comment] 2015-10-28 12:31
Thanks for the fast reply, here goes:
1.  always,
2. both versions
3. everything's still in place, looking normal and working as usual
4. nothing!

**Comment by futtta** [comment] 2015-10-28 12:33
OK, next set of questoins:
* does this happen when switching to a different theme (twenty-something)?
* does this happen with all other plugins disabled?
* is this on a live site (one which I could have a look at)?

frank

**Comment by S1SYPHOS** [comment] 2015-10-28 12:39
well, if all other plugins are disabled, it works, I'll look into this and will give you feedback, thx - stupid me :-/

**Comment by futtta** [comment] 2015-10-28 12:40
OK, as soon as you can identify the culprit, we can look into if this is fixable from AO's point of view or if this should be fixed in that plugin.

**Comment by S1SYPHOS** [comment] 2015-10-29 10:10
Alright, it's "Wordpress SEO by Yoast > Title & Metas > General Tab > Enable force rewrite titles" - with this unchecked everything's working fine!

**Comment by futtta** [comment] 2015-10-29 14:28
hmmm, seems like an output buffer conflict of some sort, I'll have a look at that.

**Comment by futtta** [comment] 2015-10-29 17:13
Installed yoast seo and enabled force rewrite titles, but can't reproduce. can you confirm this happens with just AO & Yoast with "force rewrite titles" (no other plugins)?

**Comment by S1SYPHOS** [comment] 2015-10-29 17:56
Affirmative, it's this single option. Nothing in PHP errorlog either ..

**Comment by futtta** [comment] 2015-10-30 11:55
tried on 2 systems, old debian linux w apache 2.2 and php5.2 and on a xampp install w apache 2.4 & php 5.5 and can't reproduce in either of them I'm afraid. on what system are you running?

**Comment by S1SYPHOS** [comment] 2015-11-04 10:23
hi again,
local xampp: php5.5.30 & apache2.4.17
test server: SunOS localhost 5.10 Generic_142901-13 i86pc, php5.5.29 & apache2.2.31

**Comment by futtta** [comment] 2015-11-04 12:27
weird ... what theme are you using?

**Comment by S1SYPHOS** [comment] 2015-11-04 13:12
thought about switching themes too, sadly I'm really busy right now .. I'm using a customized version of the [roots theme](https://github.com/roots/sage) (but without any bootstrap / framework-related stuff)

**Comment by futtta** [comment] 2015-11-04 13:23
when you some have time, can you briefly switch to a default wordpress theme to see if the problem persists?

**Comment by S1SYPHOS** [comment] 2015-11-06 22:21
Alright, activated Twenty Fifteen and everything's working fine - I'll check out vanilla roots theme once I have the time ... strange stuff this is indeed!

**Comment by S1SYPHOS** [comment] 2015-11-08 20:27
Well, somehow I called wp_footer twice, so .. screw me, right? I'm sorry, but thanks for your effort, especially making Autoptimize a great tool - any idea when v2.0 will be released?

Take care and thanks again!

**Comment by futtta** [comment] 2015-11-08 22:08
Great, weird things bug me ;-)

My goal is to release 2.0 before the end of the year, not sure I'll make it though as I still have to make at least one significant change (introducing an option to activate or deactivate aggregation of inline CSS & JS) which will require translations to be updated as well. And once all changes are in, this will need extensive testing off course :)

Are you running the version from Github (which is pre-2.0)?

**Closed by futtta** 2015-11-08 22:08 UTC

**Comment by S1SYPHOS** [comment] 2015-11-09 20:33
I'm pretty excited about the "ignore inline" option, and currently I
work with the github version, ready to file bugs, sir!

**Comment by futtta** [comment] 2015-11-10 08:12
"ignore inline" should go in pretty soon now. keep an eye on the [commit log](https://github.com/futtta/autoptimize/commits/master) :)

**Comment by futtta** [comment] 2015-11-17 13:39
"ignore inline" (or better; "include inline") is now committed. looking forward to your bugs ;-)
