### ISSUE TITLE
2.7 Beta 3 - ao_ccss_queue cron clears on removing rules

### ISSUE THREAD

**Issue by CymruUSA** [futtta/autoptimize#316] opened 2020-04-23 22:35 UTC
Not sure if it's expected but if the rules in CCSS are removed (Remove all Rules) upon recreation, ao_ccss_queue is no longer present in cron jobs and has to be re-added manually. The rule was created using the Advanced Cron Manager Wordpress plugin on Wordpress 5.4.

**Comment by futtta** [comment] 2020-04-24 09:31
Clearly not expected @CymruUSA ... You're the 2nd one to have this issue, but I can't reproduce (just removed all rules and the scheduled job is still there on my own site). Moreover from a code point of view [the scheduled job is only removed upon deactivation or unstallation of AO](https://github.com/futtta/autoptimize/blob/ecc0a7ecf558e7933553e904acd7af84ce8b6869/classes/autoptimizeMain.php#L629-L636) and removing all rules simply empties the wordpress option which holds the rules and does not touch the cron events so I'm kind of clueless .. Does this always happen for you?

**Comment by futtta** [comment] 2020-04-24 11:15
Just committed https://github.com/futtta/autoptimize/commit/dc1daf6abbef7230ad9e4eb2cde7babc9a668334 which systematically checks the scheduled job's existence and reschedules if not so (and if the API key is set). Could you re-download and re-install the beta and test @CymruUSA

**Comment by CymruUSA** [comment] 2020-04-24 11:20
Will do.

**Comment by CymruUSA** [comment] 2020-04-24 13:37
I think that solved the issue as I can't reproduce it now.

**Comment by futtta** [comment] 2020-04-24 13:51
great, thanks for your feedback, you're helping to make AO27 better! :)

**Closed** 2020-04-25 11:12 UTC
