### ISSUE TITLE
[2.1.99] CSS path rewriting incorrect & other issues

### ISSUE THREAD

**Issue by pbowyer** [futtta/autoptimize#94] opened 2017-05-09 19:23 UTC
I've been testing the master branch as at  6c69cca against version 2.1 and have found a few differences in the CSS minification that cause issues on our site.

In all tests the CSS options were set as below. When changing plugin versions I removed the plugin folder entirely and installed the new version, and manually cleared `cache/autoptimize/{js,css}/*` to ensure they were empty.

![image](https://cloud.githubusercontent.com/assets/89852/25867396/5962b1d8-34f1-11e7-9642-79e8b6fb9589.png)

To diff the minified files, I ran them through http://unminify.com/ before comparing.

Issues 1 & 2 are important and affect the look of the website; the others minor changes that I spotted.

### 1. Paths outside the theme directory incorrectly rewritten
This site is a direct port of a Drupal site, and some assets/CSS files are in their original locations. Before that was fine; now URL paths are incorrectly rewritten:
```diff
- background:url(//example.com/modules/system/../../misc/tree.png) no-repeat 11px center
+ background:url(//example.com/wp-content/modules/system/../../misc/tree.png) no-repeat -11px center
```
The CSS file is located outside the theme directory, in this case in `/modules/system`.

### 2. Some image positions are changed
Set to zero:
```diff
- background:url(//example.com/sites/all/themes/example/css/../images/tab-left.png) no-repeat left -76px
+ background:url(//example.com/wp-content/sites/all/themes/example/css/../images/tab-left.png) no-repeat left 0
```

Changed:
```diff
- background:url(//example.com/sites/all/themes/example/css/../images/tab-secondary.png) repeat-x left -56px
+ background:url(//example.com/wp-content/sites/all/themes/example/css/../images/tab-secondary.png) repeat-x left top
```
Flipped
```diff
ul.secondary a:hover,ul.secondary a:focus
{
-	background:url(//example.com/sites/all/themes/example/css/../images/tab-secondary.png) repeat-x left bottom
+	background:url(//example.com/wp-content/sites/all/themes/example/css/../images/tab-secondary.png) repeat-x left top
}
```
Inverted units:
```diff
- background:url(//example.com/modules/system/../../misc/tree.png) no-repeat 11px center
+ background:url(//example.com/wp-content/modules/system/../../misc/tree.png) no-repeat -11px center
```

### 3. Extraneous units added in certain places
I can't find a pattern in this, as often the new version is more succinct. However occasionally it changes `0` to `0px` as shown below:

```diff
-	-webkit-box-shadow:-32px 0 0 -31px rgba(255,255,255,1);
-	-moz-box-shadow:-32px 0 0 -31px rgba(255,255,255,1);
-	box-shadow:-32px 0 0 -31px rgba(255,255,255,1)
+	-webkit-box-shadow:-32px 0px 0px -31px rgba(255,255,255,1);
+	-moz-box-shadow:-32px 0px 0px -31px rgba(255,255,255,1);
+	box-shadow:-32px 0px 0px -31px rgba(255,255,255,1)
```

And to %:
```diff
-	background:linear-gradient(to bottom,#fefefe 0,#dddcda 100%);
+	background:linear-gradient(to bottom,#fefefe 0%,#dddcda 100%);
```

(Yes I did run the old version through the CSS Validator, just to check they were valid!)

### 4. Retains empty rules
These legacy stylesheets contain empty rules (no idea why). Before, they were stripped; now Autoptimize leaves them in:
```diff
+ #footer .section {
+ }
```

**Comment by futtta** [comment] 2017-05-09 21:29
great work @pbowyer !

some quick initial feedback:
(1) is most certainly a bug in my code, will look into that tomorrow
(2)-(4) might (or might not) be regressions in the CSS minifier AO uses ([YUI CSS minifier PHP port](https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port))

Now for that potential CSS minifier issue, could you change [L202 in autoptimize.php](https://github.com/futtta/autoptimize/blob/master/autoptimize.php#L202) from

`@include(AUTOPTIMIZE_PLUGIN_DIR.'classes/external/php/yui-php-cssmin-2.4.8-p10/cssmin.php');`
to
`@include(AUTOPTIMIZE_PLUGIN_DIR.'classes/external/php/yui-php-cssmin-2.4.8-4_fgo.php');`

This will load the version used in AO 2.1 and I would expect this might "fix" some of these ...

**Comment by pbowyer** [comment] 2017-05-10 07:11
@futta Thanks, I've tested with the previous CSS minifier and the results are:
(1) Still present
(2) Diffing 3-way (v2.1 CSS, new w new minifier, new w old minifier) I am a bit confused whether there are the same or fewer occurrences of this bug; these are the only ones I saw when comparing to the v2.1 CSS:
```diff
- background: transparent url(//example.com/modules/system/../../misc/throbber.gif) no-repeat 0 -18px;
+background: transparent url(//example.com/wp-content/modules/system/../../misc/throbber.gif) no-repeat 0 -18px no-repeat 0 -18px;
```
```diff
- background: url(//example.com/sites/all/modules/ctools/css/../images/status-active.gif) right center no-repeat
+ background: url(//example.com/wp-content/sites/all/modules/ctools/css/../images/status-active.gif) center center no-repeat
```
```diff
- background: url(//example.com/modules/system/../../misc/tree.png) no-repeat 11px center
+ background: url(//example.com/wp-content/modules/system/../../misc/tree.png) no-repeat -11px center
```

(3) No longer present

(4) Still present

Thanks!

**Comment by futtta** [comment] 2017-05-12 13:58
I just committed a fix (well, rollback actually) for (1) @pbowyer , could you test?

cfr. https://github.com/futtta/autoptimize/commit/c753971bee5a144573ff2a79c7ddd2853de1a7f4

**Comment by futtta** [comment] 2017-05-17 06:16
@pbowyer can you for (2) provide the original un-optimized CSS as well?

**Comment by zytzagoo** [comment] 2017-05-19 13:50
Running a test using this code:

```php
    public function test_some_stuff_for_issue_94()
    {
        $orig = <<<CSS
<style type="text/css">
.rule {
	webkit-box-shadow:-32px 0 0 -31px rgba(255,255,255,1);
	-moz-box-shadow:-32px 0 0 -31px rgba(255,255,255,1);
	box-shadow:-32px 0 0 -31px rgba(255,255,255,1)
}
.rule2 {
    background:linear-gradient(to bottom,#fefefe 0,#dddcda 100%);
}
#empty .thing {
}
</style>
CSS;
        $expected = '<style type="text/css" media="all">.rule{webkit-box-shadow:-32px 0 0 -31px rgba(255,255,255,1);-moz-box-shadow:-32px 0 0 -31px rgba(255,255,255,1);box-shadow:-32px 0 0 -31px rgba(255,255,255,1)}.rule2{background:linear-gradient(to bottom,#fefefe 0,#dddcda 100%)}</style><!--noptimize--><!-- Autoptimize found a problem with the HTML in your Theme, tag `title` missing --><!--/noptimize-->';

        $conf = autoptimizeConfig::instance();
        $options = [
            'justhead' => $conf->get('autoptimize_css_justhead'),
            'datauris' => $conf->get('autoptimize_css_datauris'),
            'defer' => $conf->get('autoptimize_css_defer'),
            'defer_inline' => $conf->get('autoptimize_css_defer_inline'),
            'inline' => $conf->get('autoptimize_css_inline'),
            'css_exclude' => $conf->get('autoptimize_css_exclude'),
            'cdn_url' => $conf->get('autoptimize_cdn_url'),
            'include_inline' => $conf->get('autoptimize_css_include_inline'),
            'nogooglefont' => $conf->get('autoptimize_css_nogooglefont')
        ];
        $instance = new autoptimizeStyles($orig);
        $instance->read($options);
        $instance->minify();
        $instance->cache();
        $actual = $instance->getcontent();

        $this->assertEquals($expected, $actual);
    }
```

I cannot get the behavior described in (4), that is, `#empty .thing` rule is removed properly.

Also, I don't see the issue described under (3), but that might be related to the original un-optimized css (having it would certainly help a lot with determining what's going on).

BTW, the test above is running against `yui-php-cssmin-2.4.8-p10` minifier (so, newer version, not the old one from 2.1)

**Comment by pbowyer** [comment] 2017-05-22 09:16
@futtta Sorry been busy, will test this week. Can you provide an email address I can send the unoptimized CSS to? (about 15 files)

**Comment by futtta** [comment] 2017-05-22 09:21
sure; futtta-at-gmail-dot-com

**Comment by futtta** [comment] 2017-05-23 21:48
commit https://github.com/futtta/autoptimize/commit/0199624fd39cf0b742eb2817bd92a6195356950d might fix (2) @pbowyer

**Comment by futtta** [comment] 2017-06-01 07:56
any news @pbowyer ?

**Comment by futtta** [comment] 2017-06-11 06:07
@pbowyer I'm planning to push at AO 2.2 next Sunday, so speak now or be silent forever ;-)

**Comment by pbowyer** [comment] 2017-06-14 08:04
Hi @futtta just back from holiday... will see what I can do once I've caught up with work!

**Comment by pbowyer** [comment] 2017-06-15 15:30
Hi @futtta, I have tested and can confirm that 1 & 2 are sorted. Thank you!

The site has 58 separate CSS files spread across ~20 directories which is why providing you with a copy of the unoptimised CSS proved to be somewhat challenging. I have now used https://github.com/futtta/autoptimize#filter-autoptimize_css_do_minify and aggregated into one file, which I have attached.
[autoptimize_726bd8251005170296a27661ac9200de.css.txt](https://github.com/futtta/autoptimize/files/1078124/autoptimize_726bd8251005170296a27661ac9200de.css.txt)

**Comment by futtta** [comment] 2017-06-16 05:12
OK, so (3) is still present (but is due to upstream changes because of bugs, going to let that be) and then we have (4). will look into that now.

**Comment by futtta** [comment] 2017-06-16 05:27
tested (4) by extracting that legacy file ("Page Background Styling") and enqueuing is, empty rules are not retained here?

**Comment by pbowyer** [comment] 2017-06-16 06:59
(3) isn't worth the effort to fix, the impact on file size is negligible. (4) is weird, I can reproduce it; if you enqueue the entire aggregated file do you not experience it?

**Comment by futtta** [comment] 2017-06-16 07:09
Well, I enqueued just the file that has the empty rules (having "Page Background Styling" in the opening comment block), which is how it is added at your side as well (the aggregated file is what AO generates)?

ah, but I might now what is happening; is that file a xyz.min.css or xyz-min.css? because in that case AO WILL indeed considers it minified already and will just do very light optimizations ..

**Comment by pbowyer** [comment] 2017-06-16 07:48
> ah, but I might now what is happening; is that file a xyz.min.css or xyz-min.css?

It's not, actually - it's called `/sites/all/themes/examplecom/css/page-backgrounds.css`.

I'm happy if (4) is a 'wontfix' task as it's a rare occurrence I suspect.

**Comment by pbowyer** [comment] 2017-06-16 07:55
Here's the exact file, because when I include just it, it is left intact

[page-backgrounds.css.txt](https://github.com/futtta/autoptimize/files/1080079/page-backgrounds.css.txt)

**Comment by futtta** [comment] 2017-06-16 18:52
tried with that stylesheet, still not reproducible I'm afraid .. indeed going to consider "wontfix"

**Closed** 2017-06-25 20:50 UTC
